resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/azure-pipelines
jobs:
- job: Job_1
  displayName: terraform-cli-actions
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    fetchDepth: 1
  - task: TerraformCLI@0
    displayName: terraform init
    inputs:
      command: init
      workingDirectory: deploy/terraform
      backendType: azurerm
      backendServiceArm: 71f33254-6053-434c-bb1f-9923c1681f4e
      backendAzureRmResourceGroupName: rg-terraform
      backendAzureRmStorageAccountName: tangentsaterraform
      backendAzureRmContainerName: tangentcrterraform
      backendAzureRmKey: terraform.tfstate
  - task: TerraformCLI@0
    displayName: terraform refresh
    inputs:
      command: refresh
      workingDirectory: deploy/terraform
      environmentServiceName: 71f33254-6053-434c-bb1f-9923c1681f4e
  - task: TerraformCLI@0
    displayName: terraform destroy
    retryCountOnTaskFailure: 2
    inputs:
      command: destroy
      workingDirectory: deploy/terraform
      environmentServiceName: 71f33254-6053-434c-bb1f-9923c1681f4e
...
